parameters:
    hr:
      name: 'hr'
    phone:
      name: 'phone'
    geoks_admin:
      ban_fields: []

services:
    geoks_admin.form.type.hr:
        class: Geoks\AdminBundle\Form\Custom\HrType
        arguments:
            - "%hr%"
        tags:
            - { name: form.type, alias: hr }

    geoks_admin.form.type.entity_multiple:
        class: Geoks\AdminBundle\Form\Custom\EntityMultipleType
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: entity_multiple }

    geoks_admin.form.type.phone:
        class: Geoks\AdminBundle\Form\Custom\PhoneType
        arguments:
            - "@geoks_admin.contries_phone"
        tags:
            - { name: form.type, alias: phone }

    geoks_admin.form.type.update:
        class: Geoks\ApiBundle\Form\Basic\UpdateForm
        tags:
            - { name: form.type, alias: form_update }

    geoks.flashbag.handler:
        class: Geoks\AdminBundle\Services\FlashBagHandler
        arguments: [ "@session" ]

    geoks_admin.export:
        class: Geoks\AdminBundle\Services\Export
        arguments: [ "@kernel" ]

    geoks_admin.twig_extension:
        class: Geoks\AdminBundle\Twig\AdminExtension
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@geoks.utils.string_manager"
            - "@geoks_admin.entity_fields"

        public: false
        tags:
            - { name: twig.extension }

    geoks_admin.entity_fields:
        class: Geoks\AdminBundle\Services\EntityFields
        arguments: [ "@doctrine.orm.entity_manager", "%geoks_admin.ban_fields%" ]

    geoks.user.subscriber:
        class: Geoks\AdminBundle\EventListener\Doctrine\User\UserSubscriber
        arguments: [ "@security.password_encoder" ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    geoks_admin.contries_phone:
        class: Geoks\AdminBundle\Services\CountriesPhone

    geoks_admin.import:
        class: Geoks\AdminBundle\Services\Import
        arguments: [ "@service_container" ]
