Geoks\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'geoks.user.email.assert.already_used'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: 'geoks.user.username.assert.already_used'
    properties:
        email:
            - Length:
                min: 5
                max: 255
                minMessage: "geoks.user.email.assert.tooShort"
                maxMessage: "geoks.user.email.assert.tooLong"
            - NotNull:
                message: "geoks.user.email.assert.notNull"
            - Email:
                message: "geoks.user.email.assert.type"
        firstname:
            - NotNull:
                message: "geoks.user.firstname.assert.notNull"
        lastname:
            - NotNull:
                message: "geoks.user.lastname.assert.notNull"
        plainPassword:
            - Length:
                min: 4
                max: 25
                minMessage: "geoks.user.plainPassword.assert.tooShort"
                maxMessage: "geoks.user.plainPassword.assert.tooLong"
            - NotNull:
                message: "geoks.user.plainPassword.assert.notNull"
                groups: [Registration, ResetPassword, ChangePassword]
        password:
            - Length:
                min: 4
                max: 25
                minMessage: "geoks.user.password.assert.tooShort"
                maxMessage: "geoks.user.password.assert.tooLong"
            - NotNull:
                message: "geoks.user.plainPassword.assert.notNull"
                groups: [Registration, ResetPassword, ChangePassword]
