parameters:
    geoks.user_provider.class: Geoks\ApiBundle\Security\User\EntityUserProvider
    sms.api.url: null
    sms.api.key: null
    stripe.public.key: null
    stripe.private.key: null

services:
    geoks.api.serializer:
        class: Geoks\ApiBundle\Services\Serializer
        arguments: [ "@service_container", "@jms_serializer" ]

    geoks.api.mailer:
        class: Geoks\ApiBundle\Services\AppMailer
        arguments: [ "@service_container", "@translator", "@hip_mandrill.dispatcher", "@router" ]

    geoks.api.pushnotifications:
        class: Geoks\ApiBundle\Services\PushNotify
        arguments: [ "%google.fcm.api.key%", "@translator", "@service_container" ]

    geoks.api.sms:
        class: Geoks\ApiBundle\Services\SmsSender
        arguments: ["%sms.api.url%", "%sms.api.key%", "@logger"]

    geoks.api.oauth.facebook_extension:
        class: Geoks\ApiBundle\OAuth\FacebookGrantExtension
        tags:
            - { name: fos_oauth_server.grant_extension, uri: "%facebook_grant_type%" }
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]

    geoks.user_provider:
        class: "%geoks.user_provider.class%"
        arguments: ["@doctrine", "%geoks_api.user_class%", { facebook: "%facebook_app_id%" }, "@service_container", "@session", "@security.token_storage"]

    geoks.apikey_authenticator:
        class:  Geoks\ApiBundle\Security\User\ApiKeyAuthenticator
        public: false

    geoks.uploader:
        class: Geoks\ApiBundle\Services\FileUploader

    geoks.api.stripe:
        class: Geoks\ApiBundle\Services\StripePayment
        arguments: [ "%stripe.private.key%", "%stripe.public.key%" ]